FROM node:22.11

WORKDIR /frontend

# Uncomment when not debugging and setting a
# breakpoint.
# COPY ./frontend /frontend
# RUN rm -rf /frontend/node_modules

# Comment out when not debugging and setting
# a breakpoint.
# Install dependencies
COPY ./frontend/package*.json ./

RUN npm ci

CMD ["npm", "run", "dev"]