FROM node:22.11

WORKDIR /frontend

COPY ./frontend/package*.json ./

# Run npm install and print npm-debug.log if it fails
RUN npm cache clean --force && npm install

# Now copy the rest of the app files
COPY ./frontend .

CMD ["npm", "run", "dev"]