# Generated by Django 5.1.3 on 2025-06-30 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aichatsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='session_id',
            field=models.CharField(default='AvzRC1JF4u0TCRWh0MpIig', editable=False, help_text='Unique Base64-encoded session ID', max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, unique=True),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
