# Generated by Django 5.1.3 on 2025-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aichatsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='session_id',
            field=models.CharField(default='CCdHe7M7VjiFMpnl7EHJvg', editable=False, help_text='Unique Base64-encoded session ID', max_length=24, unique=True),
        ),
    ]
