# Generated by Django 5.1.3 on 2025-06-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_aichatsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
