# Generated by Django 5.1.3 on 2025-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_aichatsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
    ]
