# Generated by Django 5.1.3 on 2025-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_aichatsession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
